.\" Hey, EMACS: -*- nroff -*-
.TH GINKGO "1" "Aug 2023" "ginkgo"
.SH NAME
ginkgo \- The ginkgo CLI
compiler
.SH SYNOPSIS
.TP
.B ginkgo
\fIflags\fR \fIpackages\fR -- \fIpass-throughs\fR
.TP
.B ginkgo
\fICOMMAND\fR
\fIoptions\fR

.SH DESCRIPTION
.PP
Ginkgo is a BDD-style Golang testing framework built to help you efficiently
write expressive and comprehensive tests.

This page documents the
.B ginkgo
CLI, which offers a number of conveniences beyond what \fBgo test\fR provides out
of the box and its usage is recommended, but not necessary.

.SH OPTIONS
.TP 4
\fBginkgo\fR or \fBginkgo run\fR \fIflags\fR \fIpackages\fR -- \fIpass-throughs\fR
Run the tests in \fIpackages\fR (or the package in the current directory).

Any arguments after \fB--\fR will be passed to the test.
Run \fBginkgo help run\fR for a description of all valid flags.

.TP 4
\fBginkgo\fR watch \fIflags\fR \fIpackages\fR -- \fIpass-throughs\fR
Watches the files in  \fIpackages\fR and re-runs tests when changes occur.

.TP 4
\fBginkgo\fR bootstrap \fIflags\fR
Bootstrap a test suite for the current package

.TP 4
\fBginkgo\fR generate \fIfilenames\fR
Generate a test file named \fIfilename\fR_test.go

If the optional \fIfilenames\fR argument is omitted, a file named after the
package in the current directory will be created.

.TP 4
\fBginkgo\fR labels \fIflags\fR \fIpackages\fR
List labels detected in the passed-in packages (or the package in the current directory).

.TP 4
\fBginkgo\fR outline \fIfilename\fR
Create an outline of Ginkgo symbols for a file.

.TP 4
\fBginkgo\fR unfocus
Recursively unfocuses any focused tests under the current directory

.SH AUTHOR
.B ginkgo
was written by Onsi Fakhouri.

This man page was written by Martín Ferrari for the Debian project.
